"""Loader/query helpers for the derived Toyota diagnostic registry.

The bundled registry is generated by ghidra_rh850_analysis `tools/gts registry` from
Toyota GTS+ plus exact live Camry evidence. It contains derived facts only; no Toyota
binary/database payloads are required on the Comma.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

DEFAULT_REGISTRY = Path(__file__).with_name("data") / "camry_2026_f33.json"
SUPPORTED_SCHEMAS = frozenset({
  "toyota-diagnostics-registry-v1", "toyota-diagnostics-registry-v2", "toyota-diagnostics-registry-v3",
  "toyota-diagnostics-registry-v4",
})
DEFAULT_UDS_TIMEOUT = 0.35
DEFAULT_UDS_RESPONSE_PENDING_TIMEOUT = 2.0

DTC_STATUS_BITS: tuple[tuple[int, str], ...] = (
  (0x01, "TEST_FAILED"),
  (0x02, "TEST_FAILED_THIS_OPERATION_CYCLE"),
  (0x04, "PENDING_DTC"),
  (0x08, "CONFIRMED_DTC"),
  (0x10, "TEST_NOT_COMPLETED_SINCE_LAST_CLEAR"),
  (0x20, "TEST_FAILED_SINCE_LAST_CLEAR"),
  (0x40, "TEST_NOT_COMPLETED_THIS_OPERATION_CYCLE"),
  (0x80, "WARNING_INDICATOR_REQUESTED"),
)


class RegistryError(ValueError):
  pass


def decode_status_bits(status: int) -> list[str]:
  if not 0 <= status <= 0xFF:
    raise RegistryError(f"status byte out of range: {status:#x}")
  return [name for bit, name in DTC_STATUS_BITS if status & bit]


def parse_int(value: str | int, what: str) -> int:
  if isinstance(value, bool) or not isinstance(value, (str, int)):
    raise RegistryError(f"{what}: expected int or numeric string, got {value!r}")
  try:
    return int(value, 0) if isinstance(value, str) else value
  except ValueError as e:
    raise RegistryError(f"{what}: invalid integer: {value!r}") from e


def parse_hex_key(value: str, what: str) -> int:
  text = value.strip()
  try:
    if text.lower().startswith("0x"):
      return int(text, 16)
    if re.fullmatch(r"[0-9A-Fa-f]{4}", text):
      return int(text, 16)
    return int(text, 10)
  except ValueError as e:
    raise RegistryError(f"{what}: invalid numeric key {value!r}") from e


def parse_bytes(value: str, what: str) -> bytes:
  if not isinstance(value, str) or not value.strip():
    raise RegistryError(f"{what}: expected non-empty hex string")
  try:
    data = bytes.fromhex(value.replace(" ", ""))
  except ValueError as e:
    raise RegistryError(f"{what}: invalid hex: {value!r}") from e
  if not data:
    raise RegistryError(f"{what}: empty payload")
  return data


@dataclass(frozen=True)
class EcuSpec:
  key: str
  name: str
  address: int
  category_id: int | None = None
  functional_response: int | None = None


@dataclass(frozen=True)
class Guard:
  ecu_key: str
  did: int
  contains_ascii: str

  @property
  def contains(self) -> bytes:
    return self.contains_ascii.encode("ascii")

  @property
  def contains_hex(self) -> str:
    # Historical helper name: the exact F181 guard is an ASCII substring, not hex bytes.
    return self.contains_ascii


@dataclass(frozen=True)
class Profile:
  path: Path
  document: dict[str, Any]
  name: str
  vehicle: str
  bus: int
  fault_status_mask: int
  ecus: tuple[EcuSpec, ...]
  guard: Guard

  @property
  def uds_timeout(self) -> float:
    return DEFAULT_UDS_TIMEOUT

  @property
  def uds_response_pending_timeout(self) -> float:
    return DEFAULT_UDS_RESPONSE_PENDING_TIMEOUT

  @property
  def dtc_clear(self) -> dict[str, Any]:
    return self.document["profile"]["dtc_clear"]

  @property
  def gts_can_topology(self) -> dict[str, Any] | None:
    return self.document["profile"].get("gts_can_topology")

  def observed_identity(self, ecu: EcuSpec | str | int) -> dict[str, Any] | None:
    spec = ecu if isinstance(ecu, EcuSpec) else self.lookup_ecu(ecu)
    raw = next(row for row in self.document["profile"]["ecus"] if row["key"] == spec.key)
    identity = raw.get("observed_identity")
    return identity if isinstance(identity, dict) else None

  @property
  def legislated_responders(self) -> frozenset[int]:
    return frozenset(self.dtc_clear["functional_obd"]["expected_responders"])

  @property
  def mode04_request(self) -> bytes:
    return bytes.fromhex(self.dtc_clear["functional_obd"]["mode04_request"])

  def scanned_ecus(self) -> tuple[EcuSpec, ...]:
    # This profile's ECU list is the exact live-validated sweep, in preserved order.
    return self.ecus

  def lookup_ecu(self, ref: str | int) -> EcuSpec:
    if isinstance(ref, int):
      matches = [ecu for ecu in self.ecus if ecu.address == ref]
    else:
      text = ref.strip()
      try:
        address = int(text, 0) if text.lower().startswith("0x") else None
      except ValueError:
        address = None
      if address is not None:
        matches = [ecu for ecu in self.ecus if ecu.address == address]
      else:
        needle = text.casefold()
        matches = [ecu for ecu in self.ecus if needle in {ecu.key.casefold(), ecu.name.casefold()}]
        if not matches:
          matches = [ecu for ecu in self.ecus if ecu.category_id is not None and needle == self.category(ecu)["category"]["name"].casefold()]
    if len(matches) == 1:
      return matches[0]
    if not matches:
      suggestions = self.suggest_ecus(str(ref))
      hint = ""
      if suggestions:
        hint = "; did you mean " + ", ".join(f"{ecu.key} ({ecu.name})" for ecu in suggestions) + "?"
      raise RegistryError(f"no ECU matches {ref!r}{hint}")
    raise RegistryError(f"ambiguous ECU {ref!r}: {', '.join(ecu.key for ecu in matches)}")

  def name_for(self, address: int) -> str:
    try:
      return self.lookup_ecu(address).name
    except RegistryError:
      return f"ECU {address:#05x}"

  def category(self, ecu: EcuSpec | str | int) -> dict[str, Any] | None:
    spec = ecu if isinstance(ecu, EcuSpec) else self.lookup_ecu(ecu)
    if spec.category_id is None:
      return None
    return self.document["catalogs"].get(str(spec.category_id))

  def dids(self, ecu: EcuSpec | str | int) -> dict[str, list[dict[str, Any]]]:
    category = self.category(ecu)
    return {} if category is None else category["dids"]

  def dtcs(self, ecu: EcuSpec | str | int) -> dict[str, list[dict[str, Any]]]:
    category = self.category(ecu)
    return {} if category is None else category["dtcs"]

  def active_tests(self, ecu: EcuSpec | str | int) -> list[dict[str, Any]]:
    category = self.category(ecu)
    return [] if category is None else category.get("active_tests", [])

  def functions(self, ecu: EcuSpec | str | int) -> list[dict[str, Any]]:
    category = self.category(ecu)
    return [] if category is None else category.get("functions", [])

  def roles(self, ecu: EcuSpec | str | int) -> list[dict[str, Any]]:
    category = self.category(ecu)
    return [] if category is None else category.get("roles", [])

  def utilities(self, ecu: EcuSpec | str | int) -> list[dict[str, Any]]:
    category = self.category(ecu)
    if category is None:
      return []
    explicit = category.get("utilities")
    if isinstance(explicit, list):
      return explicit
    # v1-v3 registries expose routine Active Tests but no separate utility catalog.
    return [row for row in category.get("active_tests", []) if row.get("kind") == "routine"]

  def suggest_ecus(self, ref: str, limit: int = 5) -> list[EcuSpec]:
    import difflib
    needle = ref.casefold()
    keyed: dict[str, EcuSpec] = {}
    for ecu in self.ecus:
      for label in (ecu.key, ecu.name, f"0x{ecu.address:X}"):
        keyed[label.casefold()] = ecu
      category = self.category(ecu)
      if category is not None:
        meta = category.get("category", {})
        for label in (meta.get("name"), meta.get("database")):
          if label:
            keyed[str(label).casefold()] = ecu
    matches = difflib.get_close_matches(needle, list(keyed), n=limit, cutoff=0.35)
    out: list[EcuSpec] = []
    for match in matches:
      ecu = keyed[match]
      if ecu not in out:
        out.append(ecu)
    return out

  def resolve_did(self, ecu: EcuSpec | str | int, query: str) -> tuple[int, list[dict[str, Any]]]:
    dids = self.dids(ecu)
    try:
      did = parse_hex_key(query, "DID")
    except RegistryError:
      did = None
    if did is not None:
      return did, dids.get(f"0x{did:04X}", [])

    needle = query.casefold()
    exact: dict[int, list[dict[str, Any]]] = {}
    fuzzy: dict[int, list[dict[str, Any]]] = {}
    for key, rows in dids.items():
      number = int(key, 16)
      for row in rows:
        name = str(row.get("name") or "")
        if name.casefold() == needle:
          exact.setdefault(number, rows)
        elif needle in name.casefold():
          fuzzy.setdefault(number, rows)
    matches = exact or fuzzy
    if len(matches) == 1:
      return next(iter(matches.items()))
    if not matches:
      raise RegistryError(f"no DID matches {query!r}")
    raise RegistryError(f"DID name {query!r} maps to multiple DIDs: {', '.join(f'0x{x:04X}' for x in matches)}")

  def lookup_active_test(self, ecu: EcuSpec | str | int, query: str, kind: str | None = None) -> dict[str, Any]:
    tests = [row for row in self.active_tests(ecu) if kind is None or row.get("kind") == kind]
    try:
      item = parse_hex_key(query, "Active Test")
    except RegistryError:
      item = None
    if item is not None:
      matches = [row for row in tests if row.get("id") == item]
    else:
      needle = query.casefold()
      exact = [row for row in tests if str(row.get("name") or "").casefold() == needle]
      matches = exact or [row for row in tests if needle in str(row.get("name") or "").casefold()]
    if len(matches) == 1:
      return matches[0]
    if not matches:
      raise RegistryError(f"no Active Test matches {query!r}")
    raise RegistryError(f"ambiguous Active Test {query!r}; specify --kind or numeric ID")

  def describe_dtc(self, ecu: EcuSpec | str | int, code: str) -> list[dict[str, Any]]:
    needle = re.sub(r"[^0-9A-Za-z]", "", code).casefold()
    out = []
    for rows in self.dtcs(ecu).values():
      for row in rows:
        if re.sub(r"[^0-9A-Za-z]", "", str(row.get("code") or "")).casefold() == needle:
          out.append(row)
    return out


def _load_ecus(profile: dict[str, Any]) -> tuple[EcuSpec, ...]:
  rows = profile.get("ecus")
  if not isinstance(rows, list) or not rows:
    raise RegistryError("profile.ecus must be a non-empty list")
  ecus = tuple(EcuSpec(
    key=str(row["key"]), name=str(row["name"]), address=int(row["address"]),
    category_id=int(row["category_id"]) if "category_id" in row else None,
    functional_response=int(row["functional_response"]) if "functional_response" in row else None,
  ) for row in rows)
  if len({ecu.address for ecu in ecus}) != len(ecus) or len({ecu.key for ecu in ecus}) != len(ecus):
    raise RegistryError("profile.ecus contains duplicate key/address")
  return ecus


def available_registries(directory: Path | None = None) -> list[Path]:
  root = DEFAULT_REGISTRY.parent if directory is None else Path(directory)
  return sorted(path for path in root.glob("*.json") if path.is_file())


def _resolve_registry_path(path: str | Path) -> Path:
  candidate = Path(path)
  if candidate.exists():
    return candidate
  text = str(path)
  if "/" not in text and "\\" not in text:
    for item in available_registries():
      try:
        document = json.loads(item.read_text())
      except (OSError, json.JSONDecodeError):
        continue
      raw = document.get("profile")
      if isinstance(raw, dict) and str(raw.get("profile")) == text:
        return item
  return candidate


def load_registry(path: str | Path = DEFAULT_REGISTRY) -> Profile:
  path = _resolve_registry_path(path)
  try:
    document = json.loads(path.read_text())
  except FileNotFoundError as e:
    raise RegistryError(f"registry file not found: {path}") from e
  except json.JSONDecodeError as e:
    raise RegistryError(f"registry is not valid JSON: {path}: {e}") from e
  if document.get("schema") not in SUPPORTED_SCHEMAS:
    raise RegistryError(f"unsupported registry schema {document.get('schema')!r}")
  raw = document.get("profile")
  if not isinstance(raw, dict):
    raise RegistryError("missing profile object")
  ecus = _load_ecus(raw)
  categories = document.get("catalogs")
  if not isinstance(categories, dict):
    raise RegistryError("missing catalogs object")
  for ecu in ecus:
    if ecu.category_id is not None and str(ecu.category_id) not in categories:
      raise RegistryError(f"ECU {ecu.key} references missing category {ecu.category_id}")
  guard_row = raw.get("identity_guard")
  if not isinstance(guard_row, dict):
    raise RegistryError("missing identity_guard")
  guard = Guard(str(guard_row["ecu"]), int(guard_row["did"]), str(guard_row["contains_ascii"]))
  profile = Profile(
    path=path,
    document=document,
    name=str(raw["profile"]),
    vehicle=str(raw["vehicle"]),
    bus=int(raw["panda_bus"]),
    fault_status_mask=int(raw["fault_status_mask"]),
    ecus=ecus,
    guard=guard,
  )
  profile.lookup_ecu(guard.ecu_key)
  clear = profile.dtc_clear["functional_obd"]
  if int(clear["request_id"]) != 0x7DF or profile.mode04_request != bytes.fromhex("0104000000000000"):
    raise RegistryError("profile no longer matches the live-validated Camry Mode 04 route")
  return profile
